const categories = [
  "Ad Hominem",
  "Appeal to Authority",
  "Appeal to Emotion",
  "Appeal to Fear",
  "Appeal to Pity",
  "Ad Populum",
  "Appeal to Ridicule",
  "Bandwagon",
  "Begging the Question",
  "Black-and-White Fallacy",
  "Causal Oversimplification",
  "Doubt",
  "Exaggeration",
  "Flag-Waving",
  "Loaded Language",
  "Misrepresentation of Someone's Position",
  "Name Calling",
  "Obfuscation",
  "Red Herring",
  "Repetition",
  "Slogans",
  "Thought-terminating Cliches",
  "Whataboutism",
  "Reductio ad Hitlerum",
  "Slippery Slope",
  "Anecdotal",
  "Burden of Proof",
  "False Cause",
  "False Dichotomy",
  "Hasty Generalization",
  "Post Hoc",
  "Continuum",
  "Etymological",
  "Genetic",
  "Personal Incredulity",
  "Middle Ground",
  "Special Pleading",
  "Tu Quoque",
  "Proving Too Much",
  "Correlation Does Not Imply Causation",
  "Equivocation",
  "False Analogy",
  "False Dilemma",
  "Non Sequitur",
  "Reductio ad Absurdum",
  "Quoting Out of Context",
  "Gambling Fallacy",
  "No True Scotsman",
  "Slippery Slope",
  "Strawman"
]

export default categories;